name 'sample-cookbook'
maintainer 'Awesome Inc.'
maintainer_email 'chef@awesomeinc.com'
license 'All rights reserved'
description 'Installs/Configures sample-app'
long_description 'Installs/Configures sample-cookbook'
version '0.1.1'

depends 'users', '~1.8.2'
depends 'apache', '~0.0.5'
